version: "3.9"
services:
  mongo:
    image: mongo
    volumes:
      - ./mongo-volume:/mongo-volume

  users_service:
    image: users_service
    build: ./users
    env_file:
      - ./users/.env
    command: /bin/sh -c "npm run migrate && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  inventory_service:
    image: inventory_service
    build: ./inventory
    env_file:
      - ./inventory/.env
    command: /bin/sh -c "npm run migrate && npm start"
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - users_service

  sales_service:
    image: sales_service
    build: ./sales
    env_file:
      - ./sales/.env
    command: /bin/sh -c "npm run migrate && npm start"
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - users_service
      - inventory_service
